/*
 * Generated by dtrace(1M).
 */

#ifndef	_NET_PROVIDER_H
#define	_NET_PROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define OADPROBE_STABILITY "___dtrace_stability$oadprobe$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define OADPROBE_TYPEDEFS "___dtrace_typedefs$oadprobe$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	OADPROBE_CUSTOM(arg0) \
do { \
	__asm__ volatile(".reference " OADPROBE_TYPEDEFS); \
	__dtrace_probe$oadprobe$custom$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " OADPROBE_STABILITY); \
} while (0)
#define	OADPROBE_CUSTOM_ENABLED() \
	({ int _r = __dtrace_isenabled$oadprobe$custom$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	OADPROBE_REQUEST(arg0) \
do { \
	__asm__ volatile(".reference " OADPROBE_TYPEDEFS); \
	__dtrace_probe$oadprobe$request$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " OADPROBE_STABILITY); \
} while (0)
#define	OADPROBE_REQUEST_ENABLED() \
	({ int _r = __dtrace_isenabled$oadprobe$request$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	OADPROBE_RESPONSE(arg0) \
do { \
	__asm__ volatile(".reference " OADPROBE_TYPEDEFS); \
	__dtrace_probe$oadprobe$response$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " OADPROBE_STABILITY); \
} while (0)
#define	OADPROBE_RESPONSE_ENABLED() \
	({ int _r = __dtrace_isenabled$oadprobe$response$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$oadprobe$custom$v1$63686172202a(const char *);
extern int __dtrace_isenabled$oadprobe$custom$v1(void);
extern void __dtrace_probe$oadprobe$request$v1$63686172202a(const char *);
extern int __dtrace_isenabled$oadprobe$request$v1(void);
extern void __dtrace_probe$oadprobe$response$v1$63686172202a(const char *);
extern int __dtrace_isenabled$oadprobe$response$v1(void);

#else

#define	OADPROBE_CUSTOM(arg0) \
do { \
	} while (0)
#define	OADPROBE_CUSTOM_ENABLED() (0)
#define	OADPROBE_REQUEST(arg0) \
do { \
	} while (0)
#define	OADPROBE_REQUEST_ENABLED() (0)
#define	OADPROBE_RESPONSE(arg0) \
do { \
	} while (0)
#define	OADPROBE_RESPONSE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _NET_PROVIDER_H */
